# Generated by Django 4.2.16 on 2024-12-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_categories_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
